# 🐍 **Week 12 Supplement 2: Pandas — Full Tutorial**

Welcome to the **Pandas supplement** for Week 12! 🎓

**Pandas** is the go-to library for working with tabular data in Python — think "Excel inside Python", but far more powerful. It is built on top of NumPy.

In this notebook you will learn:
1. Series vs DataFrame
2. Creating DataFrames
3. Reading and writing files (CSV/Excel)
4. Inspecting data
5. Selecting and filtering data (`loc`, `iloc`, boolean filtering)
6. Handling missing data
7. Adding, modifying, and dropping columns
8. Sorting data
9. Grouping and aggregation
10. Merging, joining, and concatenating DataFrames
11. Working with dates and times
12. 🏭 Hands-on exercise: Production KPI data with Pandas
13. Practice exercises

Let's dive in! 🚀

## 📌 **1. Series vs DataFrame**

### 📝 Key Concepts:
- **Series** = a single labeled 1D column of data.
- **DataFrame** = a 2D table made of multiple Series (columns), like a spreadsheet.

### 📝 Install & Import

In [1]:
# Install if needed (uncomment)
# !pip install pandas

import pandas as pd
print("Pandas version:", pd.__version__)

Pandas version: 3.0.2

In [2]:
# A Series
s = pd.Series([10, 20, 30, 40], index=["a", "b", "c", "d"])
print("Series:\n", s)
print("\nValue at index 'b':", s["b"])

Series:
 a    10
b    20
c    30
d    40
dtype: int64

Value at index 'b': 20

## 📌 **2. Creating DataFrames**

In [3]:
# From a dictionary of lists
data = {
    "Name": ["Alice", "Bob", "Charlie", "Dana"],
    "Age": [25, 30, 35, 28],
    "Department": ["QA", "Production", "Maintenance", "QA"],
    "Salary": [50000, 60000, 55000, 52000],
}
df = pd.DataFrame(data)
df

      Name  Age   Department  Salary
0    Alice   25           QA   50000
1      Bob   30   Production   60000
2  Charlie   35  Maintenance   55000
3     Dana   28           QA   52000

In [4]:
# From a list of dictionaries (rows)
rows = [
    {"Station": "ST01", "Cycle_Time": 12.5},
    {"Station": "ST02", "Cycle_Time": 11.8},
    {"Station": "ST03", "Cycle_Time": 13.2},
]
df_rows = pd.DataFrame(rows)
df_rows

  Station  Cycle_Time
0    ST01        12.5
1    ST02        11.8
2    ST03        13.2

## 📌 **3. Reading and Writing Files**

Pandas can read/write CSV, Excel, JSON, SQL and more.

In [5]:
# Write our DataFrame to CSV
df.to_csv("employees.csv", index=False)

# Read it back
df_from_csv = pd.read_csv("employees.csv")
print(df_from_csv)

# Writing/reading Excel requires openpyxl:
# df.to_excel("employees.xlsx", index=False)
# df_from_excel = pd.read_excel("employees.xlsx")

      Name  Age   Department  Salary
0    Alice   25           QA   50000
1      Bob   30   Production   60000
2  Charlie   35  Maintenance   55000
3     Dana   28           QA   52000

## 📌 **4. Inspecting Data**

In [6]:
print("Shape:", df.shape)
print("\nColumns:", list(df.columns))
print("\nData types:\n", df.dtypes)
print("\nFirst 2 rows:\n", df.head(2))
print("\nSummary statistics:\n", df.describe())

Shape: (4, 4)

Columns: ['Name', 'Age', 'Department', 'Salary']

Data types:
 Name            str
Age           int64
Department      str
Salary        int64
dtype: object

First 2 rows:
     Name  Age  Department  Salary
0  Alice   25          QA   50000
1    Bob   30  Production   60000

Summary statistics:
              Age       Salary
count   4.000000      4.00000
mean   29.500000  54250.00000
std     4.203173   4349.32945
min    25.000000  50000.00000
25%    27.250000  51500.00000
50%    29.000000  53500.00000
75%    31.250000  56250.00000
max    35.000000  60000.00000

In [7]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Name        4 non-null      str
 1   Age         4 non-null      int64
 2   Department  4 non-null      str
 3   Salary      4 non-null      int64
dtypes: int64(2), str(2)
memory usage: 260.0 bytes

## 📌 **5. Selecting and Filtering Data**

### 📝 Selecting columns

In [8]:
print(df["Name"])              # single column -> Series
print(df[["Name", "Salary"]])  # multiple columns -> DataFrame

0      Alice
1        Bob
2    Charlie
3       Dana
Name: Name, dtype: str
      Name  Salary
0    Alice   50000
1      Bob   60000
2  Charlie   55000
3     Dana   52000

### 📝 `loc` (label-based) vs `iloc` (position-based)

In [9]:
print("loc (row label 1):\n", df.loc[1])
print("\niloc (first row by position):\n", df.iloc[0])
print("\nloc slice with column names:\n", df.loc[0:2, ["Name", "Department"]])

loc (row label 1):
 Name                 Bob
Age                   30
Department    Production
Salary             60000
Name: 1, dtype: object

iloc (first row by position):
 Name          Alice
Age              25
Department       QA
Salary        50000
Name: 0, dtype: object

loc slice with column names:
       Name   Department
0    Alice           QA
1      Bob   Production
2  Charlie  Maintenance

### 📝 Boolean filtering

In [10]:
high_earners = df[df["Salary"] > 52000]
print("Employees earning more than 52,000:\n", high_earners)

qa_dept = df[(df["Department"] == "QA") & (df["Age"] < 30)]
print("\nQA employees younger than 30:\n", qa_dept)

Employees earning more than 52,000:
       Name  Age   Department  Salary
1      Bob   30   Production   60000
2  Charlie   35  Maintenance   55000

QA employees younger than 30:
     Name  Age Department  Salary
0  Alice   25         QA   50000
3   Dana   28         QA   52000

## 📌 **6. Handling Missing Data**

In [11]:
import numpy as np

df_missing = pd.DataFrame({
    "Machine": ["M1", "M2", "M3", "M4"],
    "Output": [120, np.nan, 135, np.nan],
    "Defects": [3, 2, np.nan, 1],
})
print("Original:\n", df_missing)

print("\nIs null:\n", df_missing.isna())
print("\nDrop rows with any NaN:\n", df_missing.dropna())
print("\nFill NaN with 0:\n", df_missing.fillna(0))
print("\nFill NaN with column mean:\n", df_missing.fillna(df_missing.mean(numeric_only=True)))

Original:
   Machine  Output  Defects
0      M1   120.0      3.0
1      M2     NaN      2.0
2      M3   135.0      NaN
3      M4     NaN      1.0

Is null:
    Machine  Output  Defects
0    False   False    False
1    False    True    False
2    False   False     True
3    False    True    False

Drop rows with any NaN:
   Machine  Output  Defects
0      M1   120.0      3.0

Fill NaN with 0:
   Machine  Output  Defects
0      M1   120.0      3.0
1      M2     0.0      2.0
2      M3   135.0      0.0
3      M4     0.0      1.0

Fill NaN with column mean:
   Machine  Output  Defects
0      M1   120.0      3.0
1      M2   127.5      2.0
2      M3   135.0      2.0
3      M4   127.5      1.0

## 📌 **7. Adding, Modifying, and Dropping Columns**

In [12]:
df2 = df.copy()

# Add a new column
df2["Bonus"] = df2["Salary"] * 0.10

# Modify a column using a function
df2["Name_Upper"] = df2["Name"].apply(lambda x: x.upper())

# Conditional column with np.where
df2["Senior"] = np.where(df2["Age"] >= 30, "Yes", "No")

print(df2)

# Drop a column
df2 = df2.drop(columns=["Name_Upper"])
print("\nAfter dropping Name_Upper:\n", df2.columns.tolist())

      Name  Age   Department  Salary   Bonus Name_Upper Senior
0    Alice   25           QA   50000  5000.0      ALICE     No
1      Bob   30   Production   60000  6000.0        BOB    Yes
2  Charlie   35  Maintenance   55000  5500.0    CHARLIE    Yes
3     Dana   28           QA   52000  5200.0       DANA     No

After dropping Name_Upper:
 ['Name', 'Age', 'Department', 'Salary', 'Bonus', 'Senior']

## 📌 **8. Sorting Data**

In [13]:
print("Sorted by Salary (descending):\n", df.sort_values("Salary", ascending=False))
print("\nSorted by Department then Age:\n", df.sort_values(["Department", "Age"]))

Sorted by Salary (descending):
       Name  Age   Department  Salary
1      Bob   30   Production   60000
2  Charlie   35  Maintenance   55000
3     Dana   28           QA   52000
0    Alice   25           QA   50000

Sorted by Department then Age:
       Name  Age   Department  Salary
2  Charlie   35  Maintenance   55000
1      Bob   30   Production   60000
0    Alice   25           QA   50000
3     Dana   28           QA   52000

## 📌 **9. Grouping and Aggregation**

In [14]:
grouped = df.groupby("Department")["Salary"].mean()
print("Average salary per department:\n", grouped)

agg = df.groupby("Department").agg(
    avg_salary=("Salary", "mean"),
    headcount=("Name", "count"),
    max_age=("Age", "max"),
)
print("\nMulti-aggregation:\n", agg)

Average salary per department:
 Department
Maintenance    55000.0
Production     60000.0
QA             51000.0
Name: Salary, dtype: float64

Multi-aggregation:
              avg_salary  headcount  max_age
Department
Maintenance     55000.0          1       35
Production      60000.0          1       30
QA              51000.0          2       28

In [15]:
# Pivot table example
sales = pd.DataFrame({
    "Line": ["A", "A", "B", "B", "A", "B"],
    "Shift": ["Day", "Night", "Day", "Night", "Day", "Day"],
    "Units": [100, 90, 110, 95, 105, 120],
})
pivot = sales.pivot_table(values="Units", index="Line", columns="Shift", aggfunc="sum")
print(pivot)

Shift  Day  Night
Line
A      205     90
B      230     95

## 📌 **10. Merging, Joining, and Concatenating**

In [16]:
employees = pd.DataFrame({"EmpID": [1, 2, 3], "Name": ["Alice", "Bob", "Charlie"]})
salaries = pd.DataFrame({"EmpID": [1, 2, 4], "Salary": [50000, 60000, 45000]})

# Inner join (only matching EmpIDs)
inner = pd.merge(employees, salaries, on="EmpID", how="inner")
print("Inner join:\n", inner)

# Left join (keep all employees)
left = pd.merge(employees, salaries, on="EmpID", how="left")
print("\nLeft join:\n", left)

# Concatenate two DataFrames vertically
more_employees = pd.DataFrame({"EmpID": [5], "Name": ["Dana"]})
combined = pd.concat([employees, more_employees], ignore_index=True)
print("\nConcatenated:\n", combined)

Inner join:
    EmpID   Name  Salary
0      1  Alice   50000
1      2    Bob   60000

Left join:
    EmpID     Name   Salary
0      1    Alice  50000.0
1      2      Bob  60000.0
2      3  Charlie      NaN

Concatenated:
    EmpID     Name
0      1    Alice
1      2      Bob
2      3  Charlie
3      5     Dana

## 📌 **11. Working with Dates and Times**

In [17]:
dates = pd.DataFrame({
    "Date": ["2026-01-01", "2026-01-02", "2026-01-03"],
    "Output": [500, 480, 510],
})
dates["Date"] = pd.to_datetime(dates["Date"])
dates = dates.set_index("Date")
print(dates)
print("\nDay of week:\n", dates.index.day_name())

# Resample to a 2-day sum (example of time-based aggregation)
print("\n2-day resample sum:\n", dates.resample("2D").sum())

            Output
Date
2026-01-01     500
2026-01-02     480
2026-01-03     510

Day of week:
 Index(['Thursday', 'Friday', 'Saturday'], dtype='str', name='Date')

2-day resample sum:
             Output
Date
2026-01-01     980
2026-01-03     510

## 🏭 **12. Hands-On Exercise: Production KPI Data**

A production line logs daily **output** and **defect count** per shift. We'll use Pandas to calculate a simple **defect rate KPI**.

### 🎯 Goals:
1. Build a small production dataset.
2. Compute defect rate per row.
3. Find the shift with the worst average defect rate.

In [18]:
production = pd.DataFrame({
    "Date": pd.date_range("2026-08-01", periods=6, freq="D"),
    "Shift": ["Day", "Night", "Day", "Night", "Day", "Night"],
    "Output": [1200, 1100, 1250, 1050, 1300, 1150],
    "Defects": [24, 33, 20, 42, 18, 35],
})

production["Defect_Rate_%"] = (production["Defects"] / production["Output"] * 100).round(2)
print(production)

worst_shift = production.groupby("Shift")["Defect_Rate_%"].mean().idxmax()
print(f"\nShift with the highest average defect rate: {worst_shift}")

print("\nSummary by shift:\n", production.groupby("Shift")["Defect_Rate_%"].mean().round(2))

        Date  Shift  Output  Defects  Defect_Rate_%
0 2026-08-01    Day    1200       24           2.00
1 2026-08-02  Night    1100       33           3.00
2 2026-08-03    Day    1250       20           1.60
3 2026-08-04  Night    1050       42           4.00
4 2026-08-05    Day    1300       18           1.38
5 2026-08-06  Night    1150       35           3.04

Shift with the highest average defect rate: Night

Summary by shift:
 Shift
Day      1.66
Night    3.35
Name: Defect_Rate_%, dtype: float64

## 📝 **13. Practice Exercises**

Try these on your own:

1. Load `employees.csv` (created earlier) and add a column classifying employees as `"High"` or `"Low"` salary using a threshold of your choice.
2. Given the `production` DataFrame above, find the single day with the highest defect rate.
3. Create two small DataFrames representing "machines" and "maintenance logs" (joined by `MachineID`) and merge them.
4. Using `groupby`, calculate the total `Output` per `Shift` and sort the result descending.

## 🎯 **Conclusion**

In this notebook you learned:
- The difference between a Series and a DataFrame
- Creating, reading, and writing DataFrames
- Inspecting, selecting, and filtering data
- Handling missing values
- Adding/modifying columns
- Sorting, grouping, and aggregating
- Merging, joining, and concatenating DataFrames
- Basic date/time handling
- Applying Pandas to a production KPI example

### Next: **Week 12 Supplement 3 — Matplotlib Full Tutorial**
Keep Practicing! 🚀